name: "LuxPower Control & DB"
version: "1.1.16"
slug: "luxpower-control-db"
description: >-
 "The "LuxPower Control & DB" addon integrates seamlessly with the LuxPower charge control HACS integration."
url: "https://github.com/zakery292/charge_controller/blob/main/README.md"
services:
  - mqtt:need
backup: cold
stage: stable
map: 
  - addon_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: "192.168.1.135"
  mqtt_port: 1883
  mqtt_user: "hass"
  mqtt_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str