name: "LuxPower Control & DB"
version: "1.0.12"
slug: "luxpower-control-db"
description: "This add-on runs data collection and prediction scripts for LuxPower."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: "192.168.1.135"
  mqtt_port: 1883
  mqtt_user: "hass"
  mqtt_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str