name: "LuxPower Control & DB"
version: "1.0.7"
slug: "luxpower-control-db"
description: >-
 "The "LuxPower Control & DB" addon integrates seamlessly with the LuxPower charge control HACS integration. It is designed to create a database and host scripts that are crucial for calculating battery entities within the LuxPower charge control system.

  For more details on the LuxPower charge control HACS integration, visit: LuxPower Charge Control HACS Integration. Visit our readme for more information https://github.com/zakery292/charge_controller/blob/main/README.md"
services: 
  need: 
  - MQTT
backup: cold
stage: stable
map: 
  - addon_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_host: "192.168.1.135"
  mqtt_port: 1883
  mqtt_user: "hass"
  mqtt_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str